version: "3.9"

networks:
  xenpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:

  xenpot-frontend:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.frontend
    restart: always
    ports:
      - "9001:8080"
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - xenpot-backend
      - xenpot-exporter
    networks:
      - xenpot
    environment:
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
      PENPOT_PUBLIC_URI: http://localhost:9001

  xenpot-backend:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.backend
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      xenpot-postgres:
        condition: service_healthy
      xenpot-redis:
        condition: service_healthy
    networks:
      - xenpot
    environment:
      PENPOT_DATABASE_URI: postgresql://xenpot-postgres/xenpot
      PENPOT_DATABASE_USERNAME: xenpot
      PENPOT_DATABASE_PASSWORD: YourSecurePassword123
      PENPOT_REDIS_URI: redis://xenpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_SMTP_HOST: localhost
      PENPOT_SMTP_PORT: 1025
      PENPOT_SMTP_USERNAME: ""
      PENPOT_SMTP_PASSWORD: ""
      PENPOT_SMTP_TLS: false
      PENPOT_SMTP_SSL: false
      PENPOT_TELEMETRY_ENABLED: true

  xenpot-exporter:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.exporter
    restart: always
    networks:
      - xenpot
    environment:
      PENPOT_PUBLIC_URI: http://xenpot-frontend:8080
      PENPOT_REDIS_URI: redis://xenpot-redis/0

  xenpot-postgres:
    image: "postgres:15"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xenpot"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - xenpot
    environment:
      POSTGRES_DB: xenpot
      POSTGRES_USER: xenpot
      POSTGRES_PASSWORD: YourSecurePassword123

  xenpot-redis:
    image: redis:7.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - xenpot
