version: "3.9"

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:

  penpot-frontend:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.frontend
    restart: always
    ports:
      - "9001:8080"
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    environment:
      PENPOT_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
      PENPOT_PUBLIC_URI: http://localhost:9001

  penpot-backend:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.backend
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      penpot-postgres:
        condition: service_healthy
      penpot-redis:
        condition: service_healthy
    networks:
      - penpot
    environment:
      PENPOT_DATABASE_URI: postgresql://penpot-postgres/penpot
      PENPOT_DATABASE_USERNAME: penpot
      PENPOT_DATABASE_PASSWORD: YourSecurePassword123
      PENPOT_REDIS_URI: redis://penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_SMTP_HOST: localhost
      PENPOT_SMTP_PORT: 1025
      PENPOT_SMTP_USERNAME: ""
      PENPOT_SMTP_PASSWORD: ""
      PENPOT_SMTP_TLS: false
      PENPOT_SMTP_SSL: false
      PENPOT_TELEMETRY_ENABLED: true

  penpot-exporter:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.exporter
    restart: always
    networks:
      - penpot
    environment:
      PENPOT_PUBLIC_URI: http://penpot-frontend:8080
      PENPOT_REDIS_URI: redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penpot"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - penpot
    environment:
      POSTGRES_DB: penpot
      POSTGRES_USER: penpot
      POSTGRES_PASSWORD: YourSecurePassword123

  penpot-redis:
    image: redis:7.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - penpot
